# Generated by Django 5.0.4 on 2024-04-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='ref_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
