# Generated by Django 5.0.4 on 2024-04-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userdata_ref_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='dedicated_virtual_account',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
