# Generated by Django 5.0.4 on 2024-04-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='dedicated_virtual_account',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='ref_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
