# Generated by Django 5.0.4 on 2024-04-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userdata_ref_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='admin',
            field=models.BooleanField(default=True),
        ),
    ]
