# Generated by Django 5.0.4 on 2024-04-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userdata_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
